name: 23f3001601@ds.study.iitm.ac.in

on:
  workflow_dispatch:
  schedule:
    - cron: '30 10 * * *'

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Make changes (e.g., update a timestamp file)
      - name: Update Timestamp
        run: echo "Last updated at $(date)" > last-updated.txt

      # Step 3: Commit changes (prevent failure for no changes)
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet || git commit -m "Automated commit on $(date)"

      # Step 4: Push changes using PAT
      - name: Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Shashank-s1729/Scheduled-Scraping-with-GitHub-Actions.git HEAD:${{ github.ref_name }}
